GET http://localhost:3050/api/allcomites
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjMxLCJlbWFpbCI6InF1aXNwZXNhbnRvc21hdGlhc0BnbWFpbC5jb20iLCJyb2wiOiJBZG1pbmlzdHJhZG9yIiwicm9sSWQiOjEsImlhdCI6MTc1ODE0MTE3OSwiZXhwIjoxNzU4MTc3MTc5fQ.mRnv3I11ICyY3XCAS9INa003ESQaN7_0Ha75LPzTy9c