GET http://localhost:3050/api/dashboard/reporte-periodo?fecha_inicio=2022-01-01&fecha_fin=2030-12-31&comite_id=2
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjMxLCJlbWFpbCI6InF1aXNwZXNhbnRvc21hdGlhc0BnbWFpbC5jb20iLCJyb2wiOiJBZG1pbmlzdHJhZG9yIiwicm9sSWQiOjEsImlhdCI6MTc1ODI2MTA4OCwiZXhwIjoxNzU4Mjk3MDg4fQ.8u0DoAJOwXC_JM8KWRlzqD8uWlKr2FSTEfG98bZB5rw

