GET http://localhost:3050/api/montos
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjE4LCJlbWFpbCI6InNoYXJvbEBnbWFpbC5jb20iLCJyb2wiOiJVc3VhcmlvIiwicm9sSWQiOjIsImlhdCI6MTc1NzY2NDAxNCwiZXhwIjoxNzU3NzAwMDE0fQ.kjHj9yCGC7UGVyngCwKb8A-eePBIA_Tmwzqr6T3wB48

