GET http://localhost:3050/api/usuarios/18/montos/resumen
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjMxLCJlbWFpbCI6InF1aXNwZXNhbnRvc21hdGlhc0BnbWFpbC5jb20iLCJyb2wiOiJBZG1pbmlzdHJhZG9yIiwicm9sSWQiOjEsImlhdCI6MTc1ODA4NDMyMCwiZXhwIjoxNzU4MTIwMzIwfQ.j6MgpM4ROtC1pXntBNZy9DVikNW2juSNOL5NWhpiybI